### ISSUE TITLE
How can I run the C version?

### ISSUE THREAD

**Issue by Julia-Melgare** [peterbraden/genetic-lisa#6]
Hello. I wanted to run the C code for the purpose of studying and experimenting purposes. However when I compiled the code I got a segmentation fault, and I noticed some files that are referenced in the code seem to be missing from this repository (mldata, for example). Can these files be made available? Or rather, what would be the proper process for successfully running the C version? Thank you in advance.

**Comment by peterbraden** [comment]
It's been many years since I played with the c version, and I don't remember any of this. I assume mldata was simply a bitmap version of the mona lisa image formatted to be easily imported by the c program.

You're probably best just using this as a starting point rather than trying to run it as-is.
